name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      LLVM_VERSION: 22
      CC: clang-22
      CXX: clang++-22

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
          sudo apt-get install -y clang-format clang-tidy clang-tools clang clangd libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1 liblldb-dev libllvm-ocaml-dev libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm python3-clang 

      - name: Install LLVM ${{ env.LLVM_VERSION }}
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{ env.LLVM_VERSION }}

      - name: Verify Compiler Version
        run: $CC --version

      - name: Build simulator
        env:
            LLVM_DIR: /usr/lib/llvm-22/lib/cmake/llvm
        run: make

      - name: Run unit tests
        run: make test
